# Site settings
title: Hammertime Kassel
email: hello@htks.de
description: > # this means to ignore newlines until "baseurl:"
  Erschaffe, repariere, experimentiere. Kassels DIY-Werkstatt f√ºr jedermann. Treffe Gleichgesinnte, teile dein Wissen und lerne etwas Neues.
baseurl: "" # the subpath of your site, e.g. /blog/
# twitter_username: jekyllrb
url: "https://www.hammertimekassel.de" # the base hostname & protocol for your site
# github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: "equipment"
      type: "pages"
    values:
      layout: "equipment-profile"

gems:
  - jekyll-sitemap
